artifact_location: file:C:/Users/lenovo/Desktop/XH-202625/runs/mlflow/972176474780034812
creation_time: 1782456894429
effective_trace_archival_retention: null
experiment_id: '972176474780034812'
last_update_time: 1782456894429
lifecycle_stage: active
name: C:\Users\lenovo\Desktop\XH-202625\runs
trace_location: null
workspace: default
